routes/web.php
<?php

Route::get('/call/{peer_id}', 'BroadcastController@call');

Route::get('/stream', 'BroadcastController@stream');
Route::get('/audio-server', 'BroadcastController@audioServer');

Route::get('/check-people/{email}/{cert_id}', 'Admin\CertificateController@checkPeople');
Route::get('/add-people/{email}/{full_name}/{cert_id}/{token}', 'Admin\CertificateController@addPeople');
Route::get('/download-api/{email}/{cert_id}/{token}', 'Admin\CertificateController@downloadAPI');

Route::get('/broadcast/{video_id}/{width}/{height}', 'BroadcastController@broadcast');
Route::get('/broadcast-eventon/{video_id}/{width}/{height}/{stream_id}/{bearer_token}', 'BroadcastController@broadcastEventon');

Route::redirect('/', '/login');

Route::get('/get/{cert_id}', 'Admin\CertificateController@cert_get_page');
Route::post('/download', 'Admin\CertificateController@download');
Route::get('/check/{cert_id}/{user_id}', 'Admin\CertificateController@check_by_qr');

Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.home')->with('status', session('status'));
    }

    return redirect()->route('admin.home');
});

Auth::routes(['register' => false]);

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // Certificate
    Route::delete('certificates/destroy', 'CertificateController@massDestroy')->name('certificates.massDestroy');
    Route::resource('certificates', 'CertificateController');
    Route::get('check-cert/{cert_id}', 'CertificateController@check_cert_page');

    // People
    Route::delete('people/destroy', 'PeopleController@massDestroy')->name('people.massDestroy');
    Route::resource('people', 'PeopleController');
    Route::post('excel/import', 'PeopleController@excelImport');
    Route::post('load-import', 'PeopleController@loadImport');

    // Page
    Route::delete('pages/destroy', 'PageController@massDestroy')->name('pages.massDestroy');
    Route::post('pages/media', 'PageController@storeMedia')->name('pages.storeMedia');
    Route::post('pages/ckmedia', 'PageController@storeCKEditorImages')->name('pages.storeCKEditorImages');
    Route::resource('pages', 'PageController');

    // Items
    Route::delete('items/destroy', 'ItemsController@massDestroy')->name('items.massDestroy');
    Route::resource('items', 'ItemsController');
    Route::get('items-get-select-pages-ajax', 'ItemsController@getSelectPagesAjax');

});
Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Auth', 'middleware' => ['auth']], function () {
    // Change password
    if (file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php'))) {
        Route::get('password', 'ChangePasswordController@edit')->name('password.edit');
        Route::post('password', 'ChangePasswordController@update')->name('password.update');
        Route::post('profile', 'ChangePasswordController@updateProfile')->name('password.updateProfile');
        Route::post('profile/destroy', 'ChangePasswordController@destroy')->name('password.destroyProfile');
    }
});

app/Models/Item.php
<?php

namespace App\Models;

use \DateTimeInterface;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Item extends Model
{
    use SoftDeletes;
    use HasFactory;

    public const TYPE_SELECT = [
        'name'     => 'Имя и фамилия участника',
        'cert_num' => 'Номер сертификата',
        'qr'       => 'QR для проверки сертификата',
        'got_date'       => 'Дата получения сертификата',
    ];

    public $table = 'items';

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $fillable = [
        'cert_id',
        'page_id',
        'type',
        'x_axis',
        'y_axis',
        'html_color',
        'font_size',
        'qr_size',
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    public function cert()
    {
        return $this->belongsTo(Certificate::class, 'cert_id');
    }

    public function page()
    {
        return $this->belongsTo(Page::class, 'page_id');
    }

    protected function serializeDate(DateTimeInterface $date)
    {
        return $date->format('Y-m-d H:i:s');
    }
}

app/Http/Controllers/Admin/ItemsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\MassDestroyItemRequest;
use App\Http\Requests\StoreItemRequest;
use App\Http\Requests\UpdateItemRequest;
use App\Models\Certificate;
use App\Models\Item;
use App\Models\Page;
use Gate;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class ItemsController extends Controller
{   

    public function getSelectPagesAjax (Request $r){

        $cert_id = $r->input('certid');

        $pages = Page::where('cert_id', $cert_id)->get();

        $json = array();
        $json['items'] = array();
        $i=0;
        foreach ($pages as $page) {
            $json['items'][$i]['id'] = $page->id;
            $json['items'][$i]['text'] = $page->number;
            $i++;
        }

        return response()->json($json);
    }

    public function index()
    {
        abort_if(Gate::denies('item_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $items = Item::with(['cert', 'page'])->get();

        $certificates = Certificate::get();

        $pages = Page::get();

        return view('admin.items.index', compact('items', 'certificates', 'pages'));
    }

    public function create()
    {

        abort_if(Gate::denies('item_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $certs = Certificate::pluck('name', 'id')->prepend(trans('global.pleaseSelect'), '');

        $pages = Page::pluck('number', 'id')->prepend(trans('global.pleaseSelect'), '');

        return view('admin.items.create', compact('certs', 'pages'));
    }

    public function store(StoreItemRequest $request)
    {
        $item = Item::create($request->all());

        return redirect()->route('admin.items.index');
    }

    public function edit(Item $item)
    {
        abort_if(Gate::denies('item_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $certs = Certificate::pluck('name', 'id')->prepend(trans('global.pleaseSelect'), '');

        $pages = Page::pluck('number', 'id')->prepend(trans('global.pleaseSelect'), '');

        $item->load('cert', 'page');

        return view('admin.items.edit', compact('certs', 'pages', 'item'));
    }

    public function update(UpdateItemRequest $request, Item $item)
    {
        $item->update($request->all());

        return back();
    }

    public function show(Item $item)
    {
        abort_if(Gate::denies('item_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $item->load('cert', 'page');

        return view('admin.items.show', compact('item'));
    }

    public function destroy(Item $item)
    {
        abort_if(Gate::denies('item_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $item->delete();

        return back();
    }

    public function massDestroy(MassDestroyItemRequest $request)
    {
        Item::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }
}

resources/views/admin/items/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('cruds.item.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.items.store") }}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label class="required" for="cert_id">{{ trans('cruds.item.fields.cert') }}</label>
                <select class="form-control select2 {{ $errors->has('cert') ? 'is-invalid' : '' }}" name="cert_id" id="cert_id" required>
                    @foreach($certs as $id => $entry)
                        <option value="{{ $id }}" {{ old('cert_id') == $id ? 'selected' : '' }}>{{ $entry }}</option>
                    @endforeach
                </select>
                @if($errors->has('cert'))
                    <span class="text-danger">{{ $errors->first('cert') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.item.fields.cert_helper') }}</span>
            </div>
            <div class="form-group" id="page_id_ajax_div">
                <label class="required" for="page_id">{{ trans('cruds.item.fields.page') }}</label>
                <select class="select2 form-control {{ $errors->has('page') ? 'is-invalid' : '' }}" name="page_id" id="page_id" required>

                </select>
                @if($errors->has('page'))
                    <span class="text-danger">{{ $errors->first('page') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.item.fields.page_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required">{{ trans('cruds.item.fields.type') }}</label>
                <select class="form-control {{ $errors->has('type') ? 'is-invalid' : '' }}" name="type" id="type" required>
                    <option value disabled {{ old('type', null) === null ? 'selected' : '' }}>{{ trans('global.pleaseSelect') }}</option>
                    @foreach(App\Models\Item::TYPE_SELECT as $key => $label)
                        <option value="{{ $key }}" {{ old('type', 'name') === (string) $key ? 'selected' : '' }}>{{ $label }}</option>
                    @endforeach
                </select>
                @if($errors->has('type'))
                    <span class="text-danger">{{ $errors->first('type') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.item.fields.type_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="qr_size">{{ trans('cruds.item.fields.qr_size') }}</label>
                <input class="form-control {{ $errors->has('qr_size') ? 'is-invalid' : '' }}" type="number" name="qr_size" id="qr_size" value="{{ old('qr_size', '50') }}" step="1">
                @if($errors->has('qr_size'))
                    <span class="text-danger">{{ $errors->first('qr_size') }}</span>
                @endif
            </div>
            <div class="form-group">
                <label for="x_axis">{{ trans('cruds.item.fields.x_axis') }}</label>
                <input class="form-control {{ $errors->has('x_axis') ? 'is-invalid' : '' }}" type="number" name="x_axis" id="x_axis" value="{{ old('x_axis', '0') }}" step="1">
                @if($errors->has('x_axis'))
                    <span class="text-danger">{{ $errors->first('x_axis') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.item.fields.x_axis_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="y_axis">{{ trans('cruds.item.fields.y_axis') }}</label>
                <input class="form-control {{ $errors->has('y_axis') ? 'is-invalid' : '' }}" type="number" name="y_axis" id="y_axis" value="{{ old('y_axis', '0') }}" step="1">
                @if($errors->has('y_axis'))
                    <span class="text-danger">{{ $errors->first('y_axis') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.item.fields.y_axis_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="html_color">{{ trans('cruds.item.fields.html_color') }}</label>
                <input class="form-control {{ $errors->has('html_color') ? 'is-invalid' : '' }}" type="text" name="html_color" id="html_color" value="{{ old('html_color', '#ffffff') }}">
                @if($errors->has('html_color'))
                    <span class="text-danger">{{ $errors->first('html_color') }}</span>
                @endif
            </div>
            <div class="form-group">
                <label for="font_size">{{ trans('cruds.item.fields.font_size') }}</label>
                <input class="form-control {{ $errors->has('font_size') ? 'is-invalid' : '' }}" type="number" name="font_size" id="font_size" value="{{ old('font_size', '18') }}" step="1">
                @if($errors->has('font_size'))
                    <span class="text-danger">{{ $errors->first('font_size') }}</span>
                @endif
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>
@endsection

@section('scripts')
    <script>
        $( document ).ready(function() {
            $('#cert_id').on('select2:select', function (e) {
                $('#page_id').select2({
                  ajax: {
                    url: '/admin/items-get-select-pages-ajax',
                    data: function (params) {
                        var query = {
                            certid: e.params.data.id,
                        }
                        return query;
                    },
                    dataType: 'json',
                    type: "GET",
                    processResults: function (data) {
                        return {
                            results: $.map(data.items, function (item) {
                                return {
                                    text: "Страница "+item.text,
                                    id: item.id
                                }
                            })
                        };
                    }
                  }
                });
            });
        });
    </script>
@endsection

resources/views/admin/items/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.edit') }} {{ trans('cruds.item.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.items.update", [$item->id]) }}" enctype="multipart/form-data">
            @method('PUT')
            @csrf
            <div class="form-group">
                <label class="required" for="cert_id">{{ trans('cruds.item.fields.cert') }}</label>
                <select class="form-control select2 {{ $errors->has('cert') ? 'is-invalid' : '' }}" name="cert_id" id="cert_id" required>
                    @foreach($certs as $id => $entry)
                        <option value="{{ $id }}" {{ (old('cert_id') ? old('cert_id') : $item->cert->id ?? '') == $id ? 'selected' : '' }}>{{ $entry }}</option>
                    @endforeach
                </select>
                @if($errors->has('cert'))
                    <span class="text-danger">{{ $errors->first('cert') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.item.fields.cert_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="page_id">{{ trans('cruds.item.fields.page') }}</label>
                <select class="form-control select2 {{ $errors->has('page') ? 'is-invalid' : '' }}" name="page_id" id="page_id" required>

                </select>
                @if($errors->has('page'))
                    <span class="text-danger">{{ $errors->first('page') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.item.fields.page_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required">{{ trans('cruds.item.fields.type') }}</label>
                <select class="form-control {{ $errors->has('type') ? 'is-invalid' : '' }}" name="type" id="type" required>
                    <option value disabled {{ old('type', null) === null ? 'selected' : '' }}>{{ trans('global.pleaseSelect') }}</option>
                    @foreach(App\Models\Item::TYPE_SELECT as $key => $label)
                        <option value="{{ $key }}" {{ old('type', $item->type) === (string) $key ? 'selected' : '' }}>{{ $label }}</option>
                    @endforeach
                </select>
                @if($errors->has('type'))
                    <span class="text-danger">{{ $errors->first('type') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.item.fields.type_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="qr_size">{{ trans('cruds.item.fields.qr_size') }}</label>
                <input class="form-control {{ $errors->has('qr_size') ? 'is-invalid' : '' }}" type="number" name="qr_size" id="qr_size" value="{{ old('qr_size', $item->qr_size) }}" step="1">
                @if($errors->has('qr_size'))
                    <span class="text-danger">{{ $errors->first('qr_size') }}</span>
                @endif
            </div>
            <div class="form-group">
                <label for="x_axis">{{ trans('cruds.item.fields.x_axis') }}</label>
                <input class="form-control {{ $errors->has('x_axis') ? 'is-invalid' : '' }}" type="number" name="x_axis" id="x_axis" value="{{ old('x_axis', $item->x_axis) }}" step="1">
                @if($errors->has('x_axis'))
                    <span class="text-danger">{{ $errors->first('x_axis') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.item.fields.x_axis_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="y_axis">{{ trans('cruds.item.fields.y_axis') }}</label>
                <input class="form-control {{ $errors->has('y_axis') ? 'is-invalid' : '' }}" type="number" name="y_axis" id="y_axis" value="{{ old('y_axis', $item->y_axis) }}" step="1">
                @if($errors->has('y_axis'))
                    <span class="text-danger">{{ $errors->first('y_axis') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.item.fields.y_axis_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="html_color">{{ trans('cruds.item.fields.html_color') }}</label>
                <input class="form-control {{ $errors->has('html_color') ? 'is-invalid' : '' }}" type="text" name="html_color" id="html_color" value="{{ old('html_color', $item->html_color) }}">
                @if($errors->has('html_color'))
                    <span class="text-danger">{{ $errors->first('html_color') }}</span>
                @endif
            </div>
            <div class="form-group">
                <label for="font_size">{{ trans('cruds.item.fields.font_size') }}</label>
                <input class="form-control {{ $errors->has('font_size') ? 'is-invalid' : '' }}" type="number" name="font_size" id="font_size" value="{{ old('font_size', $item->font_size) }}" step="1">
                @if($errors->has('font_size'))
                    <span class="text-danger">{{ $errors->first('font_size') }}</span>
                @endif
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>
@endsection

@section('scripts')
    <script>
        $( document ).ready(function() {
            $('#cert_id').on('select2:select', function (e) {
                $('#page_id').select2({
                  ajax: {
                    url: '/admin/items-get-select-pages-ajax',
                    data: function (params) {
                        var query = {
                            certid: e.params.data.id,
                        }
                        return query;
                    },
                    dataType: 'json',
                    type: "GET",
                    processResults: function (data) {
                        return {
                            results: $.map(data.items, function (item) {
                                return {
                                    text: "Страница "+item.text,
                                    id: item.id
                                }
                            })
                        };
                    }
                  }
                });
                $("#page_id").select2("trigger", "select", {
                data: { id: "", text: "Выберите страницу" }
                });
            });
        });

        $( document ).ready(function() {
            $('#page_id').select2({
              ajax: {
                url: '/admin/items-get-select-pages-ajax',
                data: function (params) {
                    var query = {
                        certid: '{{$item->cert->id}}',
                    }
                    return query;
                },
                dataType: 'json',
                type: "GET",
                processResults: function (data) {
                    return {
                        results: $.map(data.items, function (item) {
                            return {
                                text: "Страница "+item.text,
                                id: item.id
                            }
                        })
                    };
                }
              }
            });
            $("#page_id").select2("trigger", "select", {
                data: { id: "{{$item->page->id}}", text: "Страница {{$item->page->number}}" }
            });
        });
    </script>
@endsection

resources/views/admin/items/index.blade.php
@extends('layouts.admin')
@section('content')
@can('item_create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route('admin.items.create') }}">
                {{ trans('global.add') }} {{ trans('cruds.item.title_singular') }}
            </a>
        </div>
    </div>
@endcan
<div class="card">
    <div class="card-header">
        {{ trans('cruds.item.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable datatable-Item">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('cruds.item.fields.id') }}
                        </th>
                        <th>
                            {{ trans('cruds.item.fields.cert') }}
                        </th>
                        <th>
                            {{ trans('cruds.item.fields.page') }}
                        </th>
                        <th>
                            {{ trans('cruds.item.fields.type') }}
                        </th>
                        <th>
                            &nbsp;
                        </th>
                    </tr>
                    <tr>
                        <td>
                        </td>
                        <td>
                            <input class="search" type="text" placeholder="{{ trans('global.search') }}">
                        </td>
                        <td>
                            <select class="search">
                                <option value>{{ trans('global.all') }}</option>
                                @foreach($certificates as $key => $item)
                                    <option value="{{ $item->name }}">{{ $item->name }}</option>
                                @endforeach
                            </select>
                        </td>
                        <td>
                            <select class="search">
                                <option value>{{ trans('global.all') }}</option>
                                @foreach($pages as $key => $item)
                                    <option value="{{ $item->number }}">{{ $item->number }}</option>
                                @endforeach
                            </select>
                        </td>
                        <td>
                            <select class="search" strict="true">
                                <option value>{{ trans('global.all') }}</option>
                                @foreach(App\Models\Item::TYPE_SELECT as $key => $item)
                                    <option value="{{ $item }}">{{ $item }}</option>
                                @endforeach
                            </select>
                        </td>
                        <td>
                        </td>
                    </tr>
                </thead>
                <tbody>
                    @foreach($items as $key => $item)
                        <tr data-entry-id="{{ $item->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $item->id ?? '' }}
                            </td>
                            <td>
                                {{ $item->cert->name ?? '' }}
                            </td>
                            <td>
                                {{ $item->page->number ?? '' }}
                            </td>
                            <td>
                                {{ App\Models\Item::TYPE_SELECT[$item->type] ?? '' }}
                            </td>
                            <td>
                                @can('item_show')
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.items.show', $item->id) }}">
                                        {{ trans('global.view') }}
                                    </a>
                                @endcan

                                @can('item_edit')
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.items.edit', $item->id) }}">
                                        {{ trans('global.edit') }}
                                    </a>
                                @endcan

                                @can('item_delete')
                                    <form action="{{ route('admin.items.destroy', $item->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>
                                @endcan

                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>



@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('item_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.items.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    orderCellsTop: true,
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  let table = $('.datatable-Item:not(.ajaxTable)').DataTable({ buttons: dtButtons })
  $('a[data-toggle="tab"]').on('shown.bs.tab click', function(e){
      $($.fn.dataTable.tables(true)).DataTable()
          .columns.adjust();
  });
  
let visibleColumnsIndexes = null;
$('.datatable thead').on('input', '.search', function () {
      let strict = $(this).attr('strict') || false
      let value = strict && this.value ? "^" + this.value + "$" : this.value

      let index = $(this).parent().index()
      if (visibleColumnsIndexes !== null) {
        index = visibleColumnsIndexes[index]
      }

      table
        .column(index)
        .search(value, strict)
        .draw()
  });
table.on('column-visibility.dt', function(e, settings, column, state) {
      visibleColumnsIndexes = []
      table.columns(":visible").every(function(colIdx) {
          visibleColumnsIndexes.push(colIdx);
      });
  })
})

</script>
@endsection