routes/web.php
<?php

Route::get('/call/{peer_id}', 'BroadcastController@call');

Route::get('/stream', 'BroadcastController@stream');
Route::get('/audio-server', 'BroadcastController@audioServer');

Route::get('/check-people/{email}/{cert_id}', 'Admin\CertificateController@checkPeople');
Route::get('/add-people/{email}/{full_name}/{cert_id}/{token}', 'Admin\CertificateController@addPeople');
Route::get('/download-api/{email}/{cert_id}/{token}', 'Admin\CertificateController@downloadAPI');

Route::get('/broadcast/{video_id}/{width}/{height}', 'BroadcastController@broadcast');
Route::get('/broadcast-eventon/{video_id}/{width}/{height}/{stream_id}/{bearer_token}', 'BroadcastController@broadcastEventon');

Route::redirect('/', '/login');

Route::get('/get/{cert_id}', 'Admin\CertificateController@cert_get_page');
Route::post('/download', 'Admin\CertificateController@download');
Route::get('/check/{cert_id}/{user_id}', 'Admin\CertificateController@check_by_qr');

Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.home')->with('status', session('status'));
    }

    return redirect()->route('admin.home');
});

Auth::routes(['register' => false]);

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // Certificate
    Route::delete('certificates/destroy', 'CertificateController@massDestroy')->name('certificates.massDestroy');
    Route::resource('certificates', 'CertificateController');
    Route::get('check-cert/{cert_id}', 'CertificateController@check_cert_page');

    // People
    Route::delete('people/destroy', 'PeopleController@massDestroy')->name('people.massDestroy');
    Route::resource('people', 'PeopleController');
    Route::post('excel/import', 'PeopleController@excelImport');
    Route::post('load-import', 'PeopleController@loadImport');

    // Page
    Route::delete('pages/destroy', 'PageController@massDestroy')->name('pages.massDestroy');
    Route::post('pages/media', 'PageController@storeMedia')->name('pages.storeMedia');
    Route::post('pages/ckmedia', 'PageController@storeCKEditorImages')->name('pages.storeCKEditorImages');
    Route::resource('pages', 'PageController');

    // Items
    Route::delete('items/destroy', 'ItemsController@massDestroy')->name('items.massDestroy');
    Route::resource('items', 'ItemsController');
    Route::get('items-get-select-pages-ajax', 'ItemsController@getSelectPagesAjax');

});
Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Auth', 'middleware' => ['auth']], function () {
    // Change password
    if (file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php'))) {
        Route::get('password', 'ChangePasswordController@edit')->name('password.edit');
        Route::post('password', 'ChangePasswordController@update')->name('password.update');
        Route::post('profile', 'ChangePasswordController@updateProfile')->name('password.updateProfile');
        Route::post('profile/destroy', 'ChangePasswordController@destroy')->name('password.destroyProfile');
    }
});

app/Models/Certificate.php
<?php

namespace App\Models;

use \DateTimeInterface;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Certificate extends Model
{
    use SoftDeletes;
    use HasFactory;

    public $table = 'certificates';

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $fillable = [
        'name',
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    public function certificatePeople()
    {
        return $this->hasMany(Person::class, 'certificate_id', 'id');
    }

    public function certPages()
    {
        return $this->hasMany(Page::class, 'cert_id', 'id');
    }

    protected function serializeDate(DateTimeInterface $date)
    {
        return $date->format('Y-m-d H:i:s');
    }
}

app/Http/Controllers/Admin/CertificateController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\MassDestroyCertificateRequest;
use App\Http\Requests\StoreCertificateRequest;
use App\Http\Requests\UpdateCertificateRequest;
use App\Models\Certificate;
use App\Models\Page;
use App\Models\Item;
use App\Models\Person;
use Gate;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;
use Spatie\Browsershot\Browsershot;
use Carbon\Carbon;

class CertificateController extends Controller
{
    public function downloadAPI ($email, $cert_id, $token){

        if($token != "jadkadbajhbdh346tsfbjks886868ikjjhs"){
            die();
        }

        $check_query = Person::where('email', $email)->where('certificate_id', $cert_id)->count();

        if($check_query == 0){
            return back()->with('message', 'Такой email не связан ни с одним сертификатом.'); 
        }

        $person_data = Person::where('email', $email)->where('certificate_id', $cert_id)->get();

        $ar['pages'] = Page::where('cert_id', $cert_id)->orderBy('number')->get();
        $ar['name'] = $person_data[0]->name;
        $ar['cert_num'] = "C100".$person_data[0]->id;
        $ar['cert_id'] = $cert_id;
        $ar['user_id'] = $person_data[0]->id;

        $html = view('get_cert', $ar);
        $html = mb_convert_encoding($html, 'HTML-ENTITIES', 'UTF-8');

        $get_orientation = Page::where('cert_id', $cert_id)->limit(1)->get();
        $orientation = $get_orientation[0]->orientation;

        if($orientation == "land"){
            Browsershot::html($html)->showBackground()->windowSize(595, 842)->paperSize(297, 210)->save($person_data[0]->name.'.pdf');
        }
        if($orientation == "vert"){
            Browsershot::html($html)->showBackground()->windowSize(842, 595)->paperSize(210, 297)->save($person_data[0]->name.'.pdf');
        }

        Person::where('email', $email)->where('certificate_id', $cert_id)
                ->update([
                    "cert_num" => $ar['cert_num'],
                    "bergen_date" => Carbon::now()->timezone('Asia/Almaty'),
                ]);

        return response()->download(public_path($person_data[0]->name.'.pdf'))->deleteFileAfterSend(true);
    }

    public function addPeople($email, $full_name, $cert_id, $token){

        if($token == "jadkadbajhbdh346tsfbjks886868ikjjhs"){
            Person::insert([
                    'certificate_id' => $cert_id,
                    'email' => $email,
                    'name'  => $full_name
                ]);
        }
        return "success";
    }

    public function checkPeople($email, $cert_id){

        $check_count = Person::where('certificate_id', $cert_id)->where('email', $email)->count();

        if($check_count > 0){
            return "Exists";
        }else{
            return "No";
        }
    }

    public function check_by_qr ($cert_id, $user_id){

        $result = Person::where('certificate_id', $cert_id)->where('id', $user_id)->count();

        if($result > 0){
            $person_data = Person::where('certificate_id', $cert_id)->where('id', $user_id)->get();
            $ar['message'] = "Сертификат закреплен за ".$person_data[0]->name." (".$person_data[0]->email.")";
            return view('check_by_qr', $ar);
        }else{
            $ar['message'] = "Такой сертификат не найден.";
            return view('check_by_qr', $ar);
        }

    }

    public function check_cert_page ($cert_id){

        $person = Person::first();

        $ar['pages'] = Page::where('cert_id', $cert_id)->orderBy('number')->get();
        $ar['name'] = $person->name;
        $ar['cert_num'] = "C100".$person->id;
        $ar['cert_id'] = $cert_id;
        $ar['user_id'] = $person->id;

        return view('get_cert', $ar);
    }

    public function cert_get_page ($cert_id){

        $ar['cert_id'] = $cert_id;
        $cert_data = Certificate::where('id', $cert_id)->get();
        $ar['cert_name'] = $cert_data[0]->name;

        return view("form", $ar);
    }

    public function download (Request $r){

        $cert_id = $r->input('cert_id');
        $email = $r->input('email');

        $check_query = Person::where('email', $email)->where('certificate_id', $cert_id)->count();

        if($check_query == 0){
            return back()->with('message', 'Такой email не связан ни с одним сертификатом.'); 
        }

        $person_data = Person::where('email', $email)->where('certificate_id', $cert_id)->get();

        $ar['pages'] = Page::where('cert_id', $cert_id)->orderBy('number')->get();
        $ar['name'] = $person_data[0]->name;
        $ar['cert_num'] = "C100".$person_data[0]->id;
        $ar['cert_id'] = $cert_id;
        $ar['user_id'] = $person_data[0]->id;

        $html = view('get_cert', $ar);
        $html = mb_convert_encoding($html, 'HTML-ENTITIES', 'UTF-8');

        $get_orientation = Page::where('cert_id', $cert_id)->limit(1)->get();
        $orientation = $get_orientation[0]->orientation;

        if($orientation == "land"){
            Browsershot::html($html)->showBackground()->windowSize(595, 842)->paperSize(297, 210)->save($person_data[0]->name.'.pdf');
        }
        if($orientation == "vert"){
            Browsershot::html($html)->showBackground()->windowSize(842, 595)->paperSize(210, 297)->save($person_data[0]->name.'.pdf');
        }

        Person::where('email', $email)->where('certificate_id', $cert_id)
                ->update([
                    "cert_num" => $ar['cert_num'],
                    "bergen_date" => Carbon::now()->timezone('Asia/Almaty'),
                ]);

        return response()->download(public_path($person_data[0]->name.'.pdf'))->deleteFileAfterSend(true);
    }

    public function index()
    {
        abort_if(Gate::denies('certificate_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $certificates = Certificate::all();

        return view('admin.certificates.index', compact('certificates'));
    }

    public function create()
    {
        abort_if(Gate::denies('certificate_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.certificates.create');
    }

    public function store(StoreCertificateRequest $request)
    {
        $certificate = Certificate::create($request->all());

        return redirect()->route('admin.certificates.index');
    }

    public function edit(Certificate $certificate)
    {
        abort_if(Gate::denies('certificate_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.certificates.edit', compact('certificate'));
    }

    public function update(UpdateCertificateRequest $request, Certificate $certificate)
    {
        $certificate->update($request->all());

        return redirect()->route('admin.certificates.index');
    }

    public function show(Certificate $certificate)
    {
        abort_if(Gate::denies('certificate_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $certificate->load('certificatePeople', 'certPages');

        return view('admin.certificates.show', compact('certificate'));
    }

    public function destroy(Certificate $certificate)
    {
        abort_if(Gate::denies('certificate_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $certificate->delete();

        return back();
    }

    public function massDestroy(MassDestroyCertificateRequest $request)
    {
        Certificate::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }
}

resources/views/admin/certificates/relationships/certPages.blade.php
<div class="m-3">
    @can('page_create')
        <div style="margin-bottom: 10px;" class="row">
            <div class="col-lg-12">
                <a class="btn btn-success" href="{{ route('admin.pages.create') }}">
                    {{ trans('global.add') }} {{ trans('cruds.page.title_singular') }}
                </a>
            </div>
        </div>
    @endcan
    <div class="card">
        <div class="card-header">
            {{ trans('cruds.page.title_singular') }} {{ trans('global.list') }}
        </div>

        <div class="card-body">
            <div class="table-responsive">
                <table class=" table table-bordered table-striped table-hover datatable datatable-certPages">
                    <thead>
                        <tr>
                            <th width="10">

                            </th>
                            <th>
                                {{ trans('cruds.page.fields.id') }}
                            </th>
                            <th>
                                {{ trans('cruds.page.fields.cert') }}
                            </th>
                            <th>
                                {{ trans('cruds.page.fields.number') }}
                            </th>
                            <th>
                                {{ trans('cruds.page.fields.image') }}
                            </th>
                            <th>
                                {{ trans('cruds.page.fields.orientation') }}
                            </th>
                            <th>
                                &nbsp;
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($pages as $key => $page)
                            <tr data-entry-id="{{ $page->id }}">
                                <td>

                                </td>
                                <td>
                                    {{ $page->id ?? '' }}
                                </td>
                                <td>
                                    {{ $page->cert->name ?? '' }}
                                </td>
                                <td>
                                    {{ $page->number ?? '' }}
                                </td>
                                <td>
                                    @if($page->image)
                                        <a href="{{ $page->image->getUrl() }}" target="_blank" style="display: inline-block">
                                            <img src="{{ $page->image->getUrl('thumb') }}">
                                        </a>
                                    @endif
                                </td>
                                <td>
                                    {{ App\Models\Page::ORIENTATION_SELECT[$page->orientation] ?? '' }}
                                </td>
                                <td>
                                    @can('page_show')
                                        <a class="btn btn-xs btn-primary" href="{{ route('admin.pages.show', $page->id) }}">
                                            {{ trans('global.view') }}
                                        </a>
                                    @endcan

                                    @can('page_edit')
                                        <a class="btn btn-xs btn-info" href="{{ route('admin.pages.edit', $page->id) }}">
                                            {{ trans('global.edit') }}
                                        </a>
                                    @endcan

                                    @can('page_delete')
                                        <form action="{{ route('admin.pages.destroy', $page->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                            <input type="hidden" name="_method" value="DELETE">
                                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                            <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                        </form>
                                    @endcan

                                </td>

                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('page_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.pages.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    orderCellsTop: true,
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  let table = $('.datatable-certPages:not(.ajaxTable)').DataTable({ buttons: dtButtons })
  $('a[data-toggle="tab"]').on('shown.bs.tab click', function(e){
      $($.fn.dataTable.tables(true)).DataTable()
          .columns.adjust();
  });
  
})

</script>
@endsection

resources/views/admin/certificates/relationships/certificatePeople.blade.php
<div class="m-3">
    @can('person_create')
        <div style="margin-bottom: 10px;" class="row">
            <div class="col-lg-12">
                <a class="btn btn-success" href="{{ route('admin.people.create') }}">
                    {{ trans('global.add') }} {{ trans('cruds.person.title_singular') }}
                </a>
            </div>
        </div>
    @endcan
    <div class="card">
        <div class="card-header">
            {{ trans('cruds.person.title_singular') }} {{ trans('global.list') }}
        </div>

        <div class="card-body">
            <div class="table-responsive">
                <table class=" table table-bordered table-striped table-hover datatable datatable-certificatePeople">
                    <thead>
                        <tr>
                            <th width="10">

                            </th>
                            <th>
                                {{ trans('cruds.person.fields.id') }}
                            </th>
                            <th>
                                {{ trans('cruds.person.fields.email') }}
                            </th>
                            <th>
                                {{ trans('cruds.person.fields.name') }}
                            </th>
                            <th>
                                {{ trans('cruds.person.fields.certificate') }}
                            </th>
                            <th>
                                {{ trans('cruds.person.fields.cert_num') }}
                            </th>
                            <th>
                                {{ trans('cruds.person.fields.bergen_date') }}
                            </th>
                            <th>
                                &nbsp;
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($people as $key => $person)
                            <tr data-entry-id="{{ $person->id }}">
                                <td>

                                </td>
                                <td>
                                    {{ $person->id ?? '' }}
                                </td>
                                <td>
                                    {{ $person->email ?? '' }}
                                </td>
                                <td>
                                    {{ $person->name ?? '' }}
                                </td>
                                <td>
                                    {{ $person->certificate->name ?? '' }}
                                </td>
                                <td>
                                    {{ $person->cert_num ?? '' }}
                                </td>
                                <td>
                                    {{ $person->bergen_date ?? '' }}
                                </td>
                                <td>
                                    @can('person_show')
                                        <a class="btn btn-xs btn-primary" href="{{ route('admin.people.show', $person->id) }}">
                                            {{ trans('global.view') }}
                                        </a>
                                    @endcan

                                    @can('person_edit')
                                        <a class="btn btn-xs btn-info" href="{{ route('admin.people.edit', $person->id) }}">
                                            {{ trans('global.edit') }}
                                        </a>
                                    @endcan

                                    @can('person_delete')
                                        <form action="{{ route('admin.people.destroy', $person->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                            <input type="hidden" name="_method" value="DELETE">
                                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                            <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                        </form>
                                    @endcan

                                </td>

                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('person_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.people.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    orderCellsTop: true,
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  let table = $('.datatable-certificatePeople:not(.ajaxTable)').DataTable({ buttons: dtButtons })
  $('a[data-toggle="tab"]').on('shown.bs.tab click', function(e){
      $($.fn.dataTable.tables(true)).DataTable()
          .columns.adjust();
  });
  
})

</script>
@endsection